### ISSUE TITLE
fleet test subcommand broken in v0.3.5-rc4

### ISSUE THREAD

**Issue by ron1** [rancher/fleet#336]
The ``fleet test`` subcommand appears to be broken in v0.3.5-rc4. See below:

```
$ fleet_linux_amd64 test -t dev
panic: unable to redefine 'n' shorthand in "test" flagset: it's already used for "cluster-name" flag

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).AddFlag(0xc0009cc400, 0xc0007681e0)
	/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:874 +0x6f0
github.com/spf13/pflag.(*FlagSet).AddFlagSet.func1(0xc0007681e0)
	/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:887 +0xa8
github.com/spf13/pflag.(*FlagSet).VisitAll(0xc0009cc300, 0xc000b0fb40)
	/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:290 +0x94
github.com/spf13/pflag.(*FlagSet).AddFlagSet(0xc0009cc400, 0xc0009cc300)
	/go/pkg/mod/github.com/spf13/pflag@v1.0.5/flag.go:885 +0x58
github.com/spf13/cobra.(*Command).mergePersistentFlags(0xc00072c2c0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:1642 +0x92
github.com/spf13/cobra.stripFlags(0xc0001d2180, 0x2, 0x2, 0xc00072c2c0, 0x0, 0x2, 0x0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:562 +0x5a
github.com/spf13/cobra.(*Command).Find.func1(0xc00072c2c0, 0xc0001d2180, 0x2, 0x2, 0x4, 0xc0001d2180, 0x2, 0x2)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:621 +0x5c
github.com/spf13/cobra.(*Command).Find.func1(0xc00072d8c0, 0xc00013e050, 0x3, 0x3, 0x18a89ef, 0xc0009f8b00, 0xc0002f5800, 0xa)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:629 +0x11e
github.com/spf13/cobra.(*Command).Find(0xc00072d8c0, 0xc00013e050, 0x3, 0x3, 0x2, 0xc0003fc000, 0x88, 0xc0009f8840, 0xc000b0fe48, 0x18a8445)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:634 +0x8c
github.com/spf13/cobra.(*Command).initCompleteCmd(0xc00072d8c0, 0xc00013e050, 0x3, 0x3)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/custom_completions.go:167 +0x2cb
github.com/spf13/cobra.(*Command).ExecuteC(0xc00072d8c0, 0xc000136010, 0x2e37d20, 0xc00013e900)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:927 +0x10b
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:888
github.com/rancher/wrangler-cli.Main(0xc00072d8c0)
	/go/pkg/mod/github.com/rancher/wrangler-cli@v0.0.0-20200815040857-81c48cf8ab43/builder.go:73 +0x6d
```

**Comment by StrongMonkey** [comment]
Should be fixed in v0.3.5-rc5.
```
$ fleet-linux-amd64 -v
fleet version v0.3.5-rc5 (3b1da57)

$ fleet-linux-amd64 test -h
Match a bundle to a target and render the output

Usage:
  fleet test [flags]

Flags:
  -b, --bundle-file string    Location of the raw Bundle resource yaml
  -f, --file string           Location of the fleet.yaml
  -g, --group string          Cluster group to match against
  -L, --group-label strings   Cluster group labels to match against
  -h, --help                  help for test
  -l, --label strings         Cluster labels to match against
  -N, --name string           Cluster name to match against
  -q, --quiet                 Just print the match and don't print the resources
  -t, --target string         Explicit target to match

Global Flags:
      --context string            kubeconfig context for authentication
  -k, --kubeconfig string         kubeconfig for authentication
  -n, --namespace string          namespace (default "fleet-local")
      --system-namespace string   System namespace of the controller (default "fleet-system")

```
